### ISSUE TITLE
How to: .es6 to .js

### ISSUE THREAD

**Issue by aaronfrost** [6to5/grunt-6to5#17]
How do I use grunt-6to5 to compile one directory to another directory (including sub-folders), and instead of compiling the .es6 from to .es6, I want them to be .js file. Can you tell me how to do this? I can't figure it out. It seems like most people want to compile from .es6 to .js, so I am wondering if this is supported. Or, is this something that I should just do with another grunt task?

**Comment by gefinity** [comment]
unless I'm missing something profound it's all in the standard grunt files config right?

```javascript
"6to5": {
    all: {
        files: [
            {
                expand: true,
                cwd: "<%= publicDir %>",
                src: ["js/src/**/*.es6",
                dest: "<%= tmpDir %>",
                ext: ".js"
            }
        ]
    }
}
```

**Comment by sindresorhus** [comment]
Yes, it's just the standard grunt config. Read the grunt docs.

**Comment by rainabba** [comment]
Just hit this question myself and wanted to clarify that dest isn't required for the sake of the extension rename. Here's an updated example (note it's babel now and not 6to5):

In the following, sourceMap, presets and compact are also not required for a rename, but I needed to be able to source specific files with ES6 (not worrying about which files were which) so I use grunt to concat my files to my dest folder, then I target them with babel and my site targets those files. Sourcemaps were getting out of hand so I've disabled for now (since I rarely use them for debugging).

```
babel: {
    options: {
        sourceMap: false,
        presets: ['es2015'],
        compact: true
    },
    files: {
        expand: true,
        src: ['dist/scripts/**/*.es6'],
        ext: '.js'
    }
},
```
